controller_manager:
  ros__parameters:
    update_rate: 100

    sagan_drive_controller:
     type: sagan_drive_controller/SaganDriverController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
sagan_drive_controller:
  ros__parameters:
    joints:
     - RF_wheel_joint
     - RR_wheel_joint
     - LF_wheel_joint
     - LR_wheel_joint
    
    command_interfaces: 
      - velocity
    
    state_interfaces:
      - position
      - velocity
      
      
