controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
diff_drive_base_controller:
  ros__parameters:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["RF_wheel_joint", "RR_wheel_joint"]
      right_wheel_names: ["LF_wheel_joint", "LR_wheel_joint"]
      odom_frame_id: odom
      base_frame_id: base_footprint
      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0
      publish_rate: 50.0
      wheel_separation: 1.25
      #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
      wheel_radius: 0.3
