controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
diff_drive_base_controller:
  ros__parameters:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["LF_wheel_joint"]
      right_wheel_names: ["RF_wheel_joint"]
      base_frame_id: base_link
      publish_rate: 50.0
      wheel_separation: 1.25
      #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
      wheel_radius: 0.3
      use_stamped_vel: false
